steps:
  # Enable required APIs
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'services'
    - 'enable'
    - 'cloudresourcemanager.googleapis.com'
    - 'cloudfunctions.googleapis.com'
    - 'cloudbuild.googleapis.com'

  # Deploy directly to Cloud Functions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'functions'
    - 'deploy'
    - 'infer-category-v2'
    - '--gen2'
    - '--region=europe-west1'
    - '--runtime=python310'
    - '--source=.'
    - '--entry-point=infer_category'
    - '--trigger-http'
    - '--memory=2048MB'
    - '--timeout=540s'
    - '--min-instances=0'
    - '--max-instances=10'
    - '--service-account=${_SERVICE_ACCOUNT}'
    - '--set-env-vars=GCS_BUCKET=mybucket_ben_becker11,USE_GCS=true,USE_MOCK=false,TABPFN_API_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjoiMTA5M2IxZjYtZjMxZi00MGU4LWE3Y2YtZjFkYzQ2ZTRlNDExIiwiZXhwIjoxNzY4MzEyMDk4fQ.p_zt6eCClfPdqsxgE4sUk5dL5co9tDRKkzuryZ5wo8k'

substitutions:
  _SERVICE_ACCOUNT: 'banking@my-projects-406017.iam.gserviceaccount.com'  # Replace with your service account 